name: CI/CD Pipeline - Monorepo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_ENV: test
  TEST_DB_HOST: localhost
  TEST_DB_PORT: 3306
  TEST_DB_USERNAME: electridom_test
  TEST_DB_PASSWORD: electridom_test
  TEST_DB_NAME: electridom_test
  TEST_PORT: 3001
  TEST_JWT_SECRET: test-secret-key-for-ci
  TEST_JWT_EXPIRES_IN: 1h
  TEST_THROTTLE_TTL: 60
  TEST_THROTTLE_LIMIT: 10

jobs:
  backend-test:
    name: Backend Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: electridom_test
          MYSQL_USER: electridom_test
          MYSQL_PASSWORD: electridom_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: calculadora-electrica-backend/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            calculadora-electrica-backend/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('calculadora-electrica-backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install backend dependencies
        working-directory: calculadora-electrica-backend
        run: npm ci

      - name: Copy environment files
        working-directory: calculadora-electrica-backend
        run: |
          cp env.example .env
          cp env.test.example .env.test

      - name: Setup test database
        working-directory: calculadora-electrica-backend
        run: npm run setup:test-db-complete
        env:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 3306
          TEST_DB_USERNAME: electridom_test
          TEST_DB_PASSWORD: electridom_test
          TEST_DB_NAME: electridom_test

      - name: Run backend linting
        working-directory: calculadora-electrica-backend
        run: npm run lint

      - name: Run backend unit tests with coverage
        working-directory: calculadora-electrica-backend
        run: npm run test:unit:coverage
        env:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 3306
          TEST_DB_USERNAME: electridom_test
          TEST_DB_PASSWORD: electridom_test
          TEST_DB_NAME: electridom_test

      - name: Run backend e2e tests
        working-directory: calculadora-electrica-backend
        run: npm run test:e2e
        env:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 3306
          TEST_DB_USERNAME: electridom_test
          TEST_DB_PASSWORD: electridom_test
          TEST_DB_NAME: electridom_test

      - name: Build backend application
        working-directory: calculadora-electrica-backend
        run: npm run build

      - name: Upload backend coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./calculadora-electrica-backend/coverage/lcov.info
          flags: backend-unittests
          name: backend-codecov
          fail_ci_if_error: false

      - name: Check backend coverage threshold
        working-directory: calculadora-electrica-backend
        run: |
          COVERAGE=$(npx coverage-badges-cli --input=./coverage/lcov.info --output=./coverage/badges --type=cobertura)
          echo "Backend Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 40" | bc -l) )); then
            echo "❌ Backend coverage is below 40% threshold"
            exit 1
          else
            echo "✅ Backend coverage meets 40% threshold"
          fi

  frontend-test:
    name: Frontend Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    if: hashFiles('calculadora-electrica-frontend/package.json') != ''

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: calculadora-electrica-frontend/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            calculadora-electrica-frontend/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('calculadora-electrica-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        working-directory: calculadora-electrica-frontend
        run: npm ci

      - name: Run frontend linting
        working-directory: calculadora-electrica-frontend
        run: npm run lint

      - name: Run frontend tests
        working-directory: calculadora-electrica-frontend
        run: npm run test

      - name: Build frontend application
        working-directory: calculadora-electrica-frontend
        run: npm run build

  build:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Build backend
        working-directory: calculadora-electrica-backend
        run: |
          npm ci
          npm run build

      - name: Build frontend (if exists)
        working-directory: calculadora-electrica-frontend
        if: hashFiles('calculadora-electrica-frontend/package.json') != ''
        run: |
          npm ci
          npm run build

      - name: Create backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-artifact
          path: calculadora-electrica-backend/dist/
          retention-days: 30

      - name: Create frontend build artifact (if exists)
        uses: actions/upload-artifact@v4
        if: hashFiles('calculadora-electrica-frontend/package.json') != ''
        with:
          name: frontend-build-artifact
          path: calculadora-electrica-frontend/dist/
          retention-days: 30

      - name: Create Docker image
        working-directory: calculadora-electrica-backend
        run: |
          docker build -t calculadora-electrica-backend:${{ github.sha }} .
          docker tag calculadora-electrica-backend:${{ github.sha }} calculadora-electrica-backend:latest

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: |
            calculadora-electrica-backend/Dockerfile
            calculadora-electrica-backend/docker-compose.yml
          retention-days: 30
